--- !ditz.rubyforge.org,2008-03-06/project 
name: UnnamedWindowManager
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: doc
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-11-27 17:29:55.055765 Z
    - Tomohiko Sumi <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
